#!/bin/bash

# supposed to be executed after booting from live CD
# this script is supposed to turn debian's live CD
# debian-live-x.x.x-{amd64,i386}-standard.iso  
# into distro with desktop, since I am burning debian-live-x.x.x-amd64-lxde-desktop.iso  
# on 700MB cd-rw disk size of iso is important to me
# execute with sudo
# run startx as normal user after successful installation of packages
#

# resynchronize the package index files from their sources
# and install google chrome
sudo apt-get update && \
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
sudo dpkg -i google-chrome*.deb

if [ $? -ne 0 ]; then
    sudo apt-get install -f -y
fi


# resynchronize the package index files from their sources
# xfce4 packages and dependencies for jekyll
 
sudo apt-get install --no-install-recommends -y \
xserver-xorg xserver-xorg-core xfonts-base xinit x11-xserver-utils lightdm \
xfce4-panel xfdesktop4 xfwm4 xfce4-settings xfce4-session \
xfce4-power-manager xfce4-terminal xfce4-taskmanager xfce4-xkb-plugin \
tango-icon-theme thunar gvfs gvfs-backends policykit-1 udisks2 ntfs-3g unzip \
ruby2.1 ruby2.1-dev:amd64 ruby2.1-doc ruby2.1-tcltk make build-essential iceweasel \
xfce4-battery-plugin mousepad xarchiver zlib1g-dev squashfs-tools isomaster && \
sudo gem2.1 install bundler && \
cd ./doctor-jekyll && bundle install

cd /home/user/debian-scripts
sudo mkdir -p /home/user/.config/xfce4
sudo mkdir -p /home/user/wallpapers
sudo cp -R ./xfce4 /home/user/.config/
sudo cp ./xfce4/XdQawzB.png /home/user/wallpapers
sudo chown -R user:user /home/user/.config /home/user/wallpapers

if [ -f /home/user/Desktop/debian-installer-launcher.desktop ]; then
    sudo rm -f /home/user/Desktop/debian-installer-launcher.desktop
fi

sudo /home/user/debian-scripts/adei

#vim:ts=4
