#!/bin/bash

apt-get update && apt-get install -y \
build-essential cmake pkg-config \
libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev \
libgtk2.0-dev openexr libopenexr6 libopenexr-dev \
libatlas-base-dev gfortran \
libtbb2 libtbb-dev zlib1g-dbg zlib1g zlib1g-dev \
python2.7-dev wget curl unzip bzip2 git && \
wget https://bootstrap.pypa.io/get-pip.py && python2.7 get-pip.py && \
pip install numpy && \
mkdir setup && cd $_ && \
git clone https://github.com/Itseez/opencv.git && \
git clone https://github.com/Itseez/opencv_contrib.git && \
mkdir build && cd $_ && \
cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D WITH_OPENEXR=ON \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D BUILD_PYTHON_SUPPORT=ON \
-D WITH_TBB=ON \
-D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules \
-D BUILD_EXAMPLES=ON ../opencv && \
make -j4 && make install && \
ldconfig && \
ls -l /usr/local/lib/python2.7/site-packages/ && \
make clean
