#!/bin/bash

# supposed to be executed after booting from live CD
# this script is supposed to turn debian's live CD
# debian-live-x.x.x-{amd64,i386}-standard.iso  
# into distro with desktop, since I am burning debian-live-x.x.x-amd64-lxde-desktop.iso  
# on 700MB cd-rw disk size of iso is important to me
# execute with sudo
# run startx as normal user after successful installation of packages

# resynchronize the package index files from their sources
# and install dependencies for jekyll, xfce4 keyboard pluting
apt-get update && apt-get install -y iceweasel lightdm xfce4 && \
ruby ruby-dev make build-essential jekyll xfce4-xkb-plugin

# install google chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
dpkg -i google-chrome*.deb

if [ $? -ne 0 ]; then
    apt-get install -f -y
fi

mv /home/user/.config/xfce4 /home/user/.config/xfce4.backup
cp -r ./xfce4 /home/user/.config/
chown user:user /home/user/.config/xfce4

#vim:ts=4
