#!/bin/bash

fc=$(wc -l "$1" | cut -d ' ' -f 1 )
#echo $fc

tIFS=$IFS
IFS=''

cp "$1" "$1".inner

cat "$1" | while read -r line || [[ -n "$line" ]]; do

    cat "$1".inner | grep -v "$line" > "$1".inner.tmp
    mv "$1".inner.tmp "$1".inner
    
    cat "$1".inner | while read -r line2 || [[ -n "$line2" ]]; do

            tail -n +2 "$line" > "$line".tmp
            tail -n +2 "$line2" > "$line2".tmp

            echo -n "$line;$line2;"
            cmp --silent "$line".tmp "$line2".tmp && echo "files are same" || echo "files differ"

            rm -f "$line".tmp "$line2".tmp

    done

done

rm -f "$1".inner

IFS=$tIFS

#vim:ts=4
