ruby '2.1.5'
source "https://rubygems.org"

gem 'jekyll', '3.2.1'
gem 'rouge', '1.11.1'
gem 'listen', '3.0.8'
gem 'liquid', '3.0.6'
gem 'addressable', '2.4.0'
gem 'multipart-post', '2.0.0'
gem 'faraday', '0.9.2'
gem 'sawyer', '0.7.0'
gem 'octokit', '4.3.0'
gem 'jekyll-gist', '1.4.0'
gem 'jekyll-paginate', '1.1.0'